version: 2.1

orbs:
  go: circleci/go@1.7.0
  golangci-lint: timakin/golangci-lint@0.1.1

jobs:
  build:
    parameters:
      gover: 
        description: The version of the Go compiler to use.
        type: string
    docker:
      - image: circleci/golang:<< parameters.gover >>
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - go/install
      - go/load-cache
      - go/mod-download-cached
      - go/test:
          covermode: atomic
          failfast: true
          race: true
          parallel: "2"
          verbose: true
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: workspace
          paths:
            - << parameters.gover >>/test
            - << parameters.gover >>/circleci
            - << parameters.gover >>/templates
  
# Build Windows Binary
  build-windows:
    executor:
      name: win/default 
      size: "medium"
    steps:
      - checkout
      - run:
         command: go build -o circleci
         shell: bash --login -eo pipefail
      - store_artifacts:
          path: circleci
          destination: circleci

  
  # Static security testing - GoLang
  security-sast:
    docker:
      - image: securego/gosec:latest
    steps:
      - checkout
      - run: gosec -fmt junit-xml -out junit.xml ./...
      - store_test_results:
          path: .

workflows:
  main:
    jobs:
      - golangci-lint/lint
      - build

    jobs:
      - golangci-lint/lint
      
      # Static application security testing
      - security-sast:
          requires:
            - golangci-lint/lint
      
      - build:
          matrix:
            parameters:
              gover: ["1.11", "1.12", "1.13", "1.14"]
          requires:
            - security-sast
      
      - build-windows
          requires:
            - build     
      
      # Run unit tests 
      - test:
          matrix:
            parameters:
              gover: ["1.11", "1.12", "1.13"]
          requires:
            - build-windows

# jobs: 
#   build: 
#     docker: 
#       - image: circleci/golang:1.16
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD
    
#     # environment: # environment variables for the build itself
#     #   TEST_RESULTS: /tmp/test-results # path to where test results will be saved

#     # steps: # steps that comprise the `build` job
#     #   - checkout # check out source code to working directory
#     #   - run: mkdir -p $TEST_RESULTS # create the test results directory

#     #   - restore_cache: # restores saved cache if no changes are detected since last run
#     #       keys:
#     #         - go-mod-v4-{{ checksum "go.sum" }}